projects:
  appsync-test-rtfd:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: eu-west-3
        apiId: xlms62myovd3tdrnvr7fztkave
        maxDepth: 2
extensions:
  amplify:
    version: 3
